#!/usr/bin/env node

import * as fs from 'node:fs';
import * as path from 'node:path';
import { analyze } from './index.js';
import type { AnalysisResult } from './types.js';

function formatBytes(bytes: number): string {
  if (bytes >= 1024 * 1024 * 1024) {
    return `${(bytes / 1024 / 1024 / 1024).toFixed(2)} GB`;
  }
  if (bytes >= 1024 * 1024) {
    return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
  }
  if (bytes >= 1024) {
    return `${(bytes / 1024).toFixed(1)} KB`;
  }
  return `${bytes} B`;
}

function printHelp(): void {
  console.log(`
docker-context-scout v0.1.0

Analyze Docker build context size and suggest .dockerignore rules.

Usage:
  docker-context-scout [path] [options]

Arguments:
  path          Directory to analyze (default: current directory)

Options:
  --fix         Append suggested rules to .dockerignore
  --json        Output results as JSON (for CI pipelines)
  --help, -h    Show this help message

Examples:
  docker-context-scout
  docker-context-scout ./my-app --fix
  docker-context-scout /path/to/project --json
`);
}

function printPretty(result: AnalysisResult): void {
  const hr = '-'.repeat(60);

  console.log('');
  console.log('  Docker Context Scout');
  console.log(hr);
  console.log(`  Path:        ${result.analyzedPath}`);
  console.log(`  Total size:  ${formatBytes(result.totalSizeBytes)} (${result.fileCount} files)`);

  if (result.existingDockerignoreRules.length > 0) {
    console.log(`  .dockerignore: ${result.existingDockerignoreRules.length} existing rules`);
  } else {
    console.log('  .dockerignore: not found');
  }

  console.log('');
  console.log('  Top 10 items by size:');
  console.log(hr);

  const top10 = result.topOffenders.slice(0, 10);
  for (const entry of top10) {
    const type = entry.isDirectory ? 'dir ' : 'file';
    const label = `  [${type}]  ${entry.path}`;
    const size = formatBytes(entry.size).padStart(10);
    console.log(`${label.padEnd(50)} ${size}`);
  }

  if (result.suggestedRules.length > 0) {
    console.log('');
    console.log('  Suggested .dockerignore rules:');
    console.log(hr);

    for (const rule of result.suggestedRules) {
      const savings = formatBytes(rule.estimatedSavingsBytes);
      console.log(`  ${rule.pattern.padEnd(25)}  saves ~${savings.padStart(10)}  ${rule.reason}`);
    }

    console.log('');
    console.log(hr);
    console.log(
      `  Estimated context after optimization: ${formatBytes(result.estimatedReducedSizeBytes)}`
    );
    console.log(
      `  Potential reduction: ${result.reductionPercentage}% (${formatBytes(
        result.totalSizeBytes - result.estimatedReducedSizeBytes
      )})`
    );
  } else {
    console.log('');
    console.log('  No additional optimizations found. Your .dockerignore looks good.');
  }

  console.log('');
}

function applyFix(targetPath: string, result: AnalysisResult): void {
  if (result.suggestedRules.length === 0) {
    console.log('Nothing to add - no new suggestions.');
    return;
  }

  const dockerignorePath = path.join(targetPath, '.dockerignore');
  const header = '\n# Added by docker-context-scout\n';
  const lines = result.suggestedRules.map((r) => `${r.pattern}  # ${r.reason}`).join('\n');
  const block = `${header}${lines}\n`;

  if (fs.existsSync(dockerignorePath)) {
    fs.appendFileSync(dockerignorePath, block, 'utf-8');
    console.log(`Appended ${result.suggestedRules.length} rules to ${dockerignorePath}`);
  } else {
    const banner = `# .dockerignore - generated by docker-context-scout\n`;
    fs.writeFileSync(dockerignorePath, `${banner}${lines}\n`, 'utf-8');
    console.log(`Created ${dockerignorePath} with ${result.suggestedRules.length} rules`);
  }
}

function main(): void {
  const args = process.argv.slice(2);

  if (args.includes('--help') || args.includes('-h')) {
    printHelp();
    process.exit(0);
  }

  const jsonMode = args.includes('--json');
  const fixMode = args.includes('--fix');

  const positional = args.filter((a) => !a.startsWith('--') && a !== '-h');
  const targetPath = positional[0] ?? process.cwd();

  let result: AnalysisResult;
  try {
    result = analyze(targetPath);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (jsonMode) {
      console.error(JSON.stringify({ error: message }));
    } else {
      console.error(`Error: ${message}`);
    }
    process.exit(1);
  }

  if (jsonMode) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    printPretty(result);
  }

  if (fixMode) {
    applyFix(targetPath, result);
  }
}

main();
